### ISSUE TITLE
CSS não carrega aparentemente

### ISSUE THREAD

**Issue by ccostafrias** [Fellipe-Barradas/FitTrack-landing-page#5]
Abri o seu [site](https://fit-track-landing-page-fellipe-barradas.vercel.app) em alguns navegadores, porém neles todos as folhas de estilo não carregaram. Acredito que seja um erro de referência no _header_.

![image](https://user-images.githubusercontent.com/84143916/229373787-5047cf35-78f4-40b5-9275-3813a3c25517.png)

**Comment by Fellipe-Barradas** [comment]
O <a href="https://fit-track-landing-page-git-teste-fellipe-barradas.vercel.app/">site</a> foi corrigido, obrigado por me informar. Qualquer coisa, estou disponivel.
